export const INCREMENT_RED = 'INCREMENT_RED';
export const DECREMENT_RED = 'DECREMENT_RED';
export const INCREMENT_GREEN = 'INCREMENT_GREEN';
export const DECREMENT_GREEN = 'DECREMENT_GREEN';
export const INCREMENT_BLUE = 'INCREMENT_BLUE';
export const DECREMENT_BLUE = 'DECREMENT_BLUE';
